server:
  port: 9005

spring:
  application:
    name: kuke-board-article-read-service
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kuke-board-article-read-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false

endpoints:
  # command 서버들(원본 데이터를 가져오기 위함)
  kuke-board-article-service:
    url: http://127.0.0.1:9000
  kuke-board-comment-service:
    url: http://127.0.0.1:9001
  kuke-board-like-service:
    url: http://127.0.0.1:9002
  kuke-board-view-service:
    url: http://127.0.0.1:9003